messaging:
  produce:
    topic: topic1
  consume:
    topic: topic1
    subscription: topic1-subscriber1
    concurrency: 5
logging:
  level:
    root: WARN
    by.dma: DEBUG


spring:
  cloud:
    azure:
      servicebus:
        connection-string: ${AZURE_SERVICEBUS_CONNECTION_STRING}
        namespace: ${AZURE_SERVICEBUS_NAMESPACE}
